"""Public API for the non-AI Gauntlet analyzer."""

from .analysis import analyze_loaded_document, analyze_paper_text
from .action_plan import ReviewerAction, action_plan_to_markdown, build_reviewer_action_plan
from .batch import (
    BatchScanItem,
    batch_items_to_csv,
    batch_items_to_html,
    batch_items_to_json,
    build_demo_batch_items,
    build_batch_report_bundle,
    filter_batch_items,
    sort_batch_items,
)
from .benchmarks import (
    BenchmarkComparison,
    BenchmarkSample,
    CalibrationGateResult,
    CalibrationCategorySummary,
    CalibrationSuiteResult,
    evaluate_calibration_gate,
    persist_calibration_snapshot,
    list_benchmark_samples,
    run_benchmark_sample,
    run_calibration_suite,
)
from .document_loader import LoadedDocument, load_document_from_bytes, load_document_from_path
from .evidence_map import (
    ClaimEvidenceMap,
    ClaimEvidenceRow,
    build_claim_evidence_map,
    claim_evidence_map_to_markdown,
)
from .models import AnalysisReport, SourceSpan
from .report_bundle import build_report_bundle
from .refinement import ProviderSelection, RefinementReport, run_provider_refinement, run_refinement
from .repair_workshop import RepairStep, build_repair_steps, repair_workshop_to_markdown
from .reviewer_packet import build_reviewer_packet_bundle, reviewer_packet_to_html, reviewer_packet_to_markdown
from .revision_recheck import RevisionRecheckResult, recheck_repair_revision, revision_recheck_log_to_markdown
from .share import (
    DemoShareSummary,
    build_demo_share_pack,
    build_demo_share_summary,
    build_share_card_html,
    build_share_card_svg,
    build_x_post,
)
from .source_review import (
    SourceReviewItem,
    build_source_review_items,
    source_review_to_markdown,
)
from .source_reader import (
    SourceReaderAnchor,
    SourceReaderRelatedItem,
    SourceReaderView,
    build_source_reader_view,
    source_reader_to_markdown,
)
from .system_check import DiagnosticItem, SystemCheckReport, collect_system_check
from .workspace import (
    ISSUE_REVIEW_STATUSES,
    SavedRun,
    SavedRunSummary,
    delete_saved_run,
    list_saved_runs,
    load_saved_run,
    save_analysis_run,
    update_saved_run_revision_recheck,
    update_saved_run_repair_progress,
    update_saved_run_issue_review,
    update_saved_run_notes,
)

__all__ = [
    "AnalysisReport",
    "BatchScanItem",
    "BenchmarkComparison",
    "BenchmarkSample",
    "CalibrationGateResult",
    "CalibrationSuiteResult",
    "evaluate_calibration_gate",
    "persist_calibration_snapshot",
    "CalibrationCategorySummary",
    "ClaimEvidenceMap",
    "ClaimEvidenceRow",
    "DemoShareSummary",
    "DiagnosticItem",
    "LoadedDocument",
    "ISSUE_REVIEW_STATUSES",
    "ProviderSelection",
    "RefinementReport",
    "RepairStep",
    "RevisionRecheckResult",
    "ReviewerAction",
    "SavedRun",
    "SavedRunSummary",
    "SourceSpan",
    "SourceReviewItem",
    "SourceReaderAnchor",
    "SourceReaderRelatedItem",
    "SourceReaderView",
    "SystemCheckReport",
    "analyze_loaded_document",
    "analyze_paper_text",
    "action_plan_to_markdown",
    "batch_items_to_csv",
    "batch_items_to_html",
    "batch_items_to_json",
    "build_demo_batch_items",
    "build_reviewer_action_plan",
    "build_repair_steps",
    "build_batch_report_bundle",
    "build_claim_evidence_map",
    "build_report_bundle",
    "build_reviewer_packet_bundle",
    "build_demo_share_pack",
    "build_demo_share_summary",
    "build_share_card_html",
    "build_share_card_svg",
    "build_x_post",
    "build_source_review_items",
    "build_source_reader_view",
    "claim_evidence_map_to_markdown",
    "collect_system_check",
    "delete_saved_run",
    "filter_batch_items",
    "list_benchmark_samples",
    "list_saved_runs",
    "load_document_from_bytes",
    "load_document_from_path",
    "load_saved_run",
    "run_benchmark_sample",
    "run_calibration_suite",
    "run_provider_refinement",
    "run_refinement",
    "save_analysis_run",
    "sort_batch_items",
    "source_review_to_markdown",
    "source_reader_to_markdown",
    "repair_workshop_to_markdown",
    "reviewer_packet_to_html",
    "reviewer_packet_to_markdown",
    "recheck_repair_revision",
    "revision_recheck_log_to_markdown",
    "update_saved_run_revision_recheck",
    "update_saved_run_repair_progress",
    "update_saved_run_issue_review",
    "update_saved_run_notes",
]
